name: CI


on:
  
  push:
    branches: [ "master" ]
  pull_request: 
    branches: ["master"]

jobs:
  test: 
    runs-on: ubuntu-latest 
    steps: 
      - name: checkout stage 
        run: sleep 10 
    
  build: 
    needs: test
    runs-on: ubuntu-latest 
    steps: 
      - name: here we are perforimg the testing 
        run: sleep 10 
    
  deploy: 
    needs: [build,test]
    runs-on: ubuntu-latest
    steps: 
      - name: here we are performing the deploy stages 
        run: sleep 10
    
  

