name: CI


on:
  
  push:
    branches: [ "master" ]
  pull_request: 
    branches: ["master"]
env: 
  name: "this is the gloabl variable"

jobs:
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: here we are printing the global variable 
        run: echo $name
   
  

