name: CI


on:
  
  push:
    branches: [ "master" ]
  pull_request: 
    branches: ["master"]

jobs:
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 1
    steps: 
      - name: wait for the job 
        run: sleep 62
    
        
  

